StackOverflow/routes/web.php
<?php


Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/forum','ForumController');

Route::get('/forum/read/{slug}','ForumController@show')->name('forumslug');

Route::post('/comment/addComment/{forum}','CommentController@addComment')->name('addComment');

Route::post('/reply/addReply/{forum}','ReplyController@addReply')->name('addReply');

StackOverflow/app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    //
}

StackOverflow/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

StackOverflow/app/comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class comment extends Model
{
    public function commentable()
    {
    	return $this->morphTo();
    }
    public function user()
    {
    	return $this->belongsTo('App\User');
    }    
}

StackOverflow/app/forum.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Tag;
use App\User;
class forum extends Model
{
    public function tags()
    {
    	return $this->belongsToMany('App\Tag');

    }
    public function user()
    {
        return $this->belongsTo('App\User');
    }
    public function comments()
    {
    	return $this->morphMany('App\Comment','commentable');
    }
    public function replies()
    {
        return $this->morphMany('App\Reply','commentable');
    }
}

StackOverflow/app/komentar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Komentar extends Model
{
    public function commentable()
    {
    	return $this->morphTo();
    }
}

StackOverflow/app/reply.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class reply extends Model
{
    public function commentable()
    {
    	return $this->morphTo();
    }
    public function user()
    {
    	return $this->belongsTo('App\User');
    }    
}

StackOverflow/app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Forum;
use App\Comment;
use Auth;
class CommentController extends Controller
{
    public function addComment(Request $request, Forum $forum)
    {
    	$request->validate([
    		'content' => 'required|min:3',
    	]);
    	$comment = New Comment;
    	$comment->user_id = Auth::user()->id;
    	$comment->content = $request->content;

    	$forum->comments()->save($comment);

    	return back()->withInfo('Komentar Terkirim!');

    }
}

StackOverflow/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

StackOverflow/app/Http/Controllers/ForumController.php
<?php

namespace App\Http\Controllers;

use App\forum;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Tag;
use Auth;
use App\User;
class ForumController extends Controller
{
 
    public function __construct()
    {
        $this->middleware('auth')->except('index','show');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $forums = Forum::paginate(5);
        return view('forum.index', compact('forums'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $forums = Forum::orderBy('id','desc')->paginate(1);
        $tags = Tag::all();
        return view('forum.create', compact('tags','forums'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'tags' => 'required',
            'image' => 'image|mimes:jpg,jpeg,png',
        ]);

        $forums = New Forum;
        $forums->user_id = Auth::user()->id;
        $forums->title = $request->title;
        $forums->slug = Str::slug($request->title);
        $forums->description = $request->description;
        if ($request->file('image')){
            $file = $request->file('image');
            $filename = time().'.'.$file->getClientOriginalExtension();
            $location = public_path('/image');
            $file->move($location,$filename);
            $forums->image = $filename;
        }
        $forums->save();
        $forums->tags()->sync($request->tags);
        return back()->withInfo('Pertanyaan terkirim!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $forums = Forum::where('id', $slug)
                        ->orwhere('slug', $slug)
                        ->firstOrFail();
        return view('forum.show', compact('forums'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tags = Tag::all();
        $forum = Forum::find($id);
        return view('forum.edit', compact('forum','tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'tags' => 'required',
            'image' => 'image|mimes:jpg,jpeg,png',
        ]);
        $forums = Forum::find($id);
        $forums->user_id = Auth::user()->id;
        $forums->title = $request->title;
        $forums->slug = Str::slug($request->title);
        $forums->description = $request->description;
        $forums->tags = $request->tags;
        if ($request->file('image')){
            $file = $request->file('image');
            $filename = time().'.'.$file->getClientOriginalExtension();
            $location = public_path('/image');
            $file->move($location,$filename);

            $oldImage = $forums->image;
            \Storage::delete($oldImage);

            $forums->image = $filename;
        }
        $forums->save();
        $forums->tags()->sync($request->tags);
        return back();
        

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function destroy(forum $forum)
    {
        //
    }
}

StackOverflow/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

StackOverflow/app/Http/Controllers/ReplyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Forum;
use App\Reply;
use Auth;
class ReplyController extends Controller
{
    public function addReply(Request $request, Forum $forum)
    {
    	$request->validate([
    		'konten' => 'required|min:3',
    	]);
    	$reply = New Reply;
    	$reply->user_id = Auth::user()->id;
    	$reply->konten = $request->konten;

    	$forum->replies()->save($reply);

    	return back()->withInfo('Balasan Terkirim!');

    }
}

StackOverflow/resources/views/forum/create.blade.php
@extends('layouts.app')
@section('title','Buat Pertanyaan')
@section('content')
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>tinymce.init({selector:'textarea'});</script>
<div class="container">
     <div class="jumbotron" id="tc_jumbotron">
        <div class="col-md-8 offset-md-2">
          <div class="text-center"><h3 style="color: #000;">Buat Pertanyaan</h3></div><hr style="background: #000"> 
        </div>
      <div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card"> 
                <div class="card-body">
                   <form action="{{route('forum.store')}}" method="post"  enctype="multipart/form-data">
                      {{csrf_field()}}
                    <div class="form-group">
                      <input type="text" id="tc_input" class="form-control" name="title" placeholder="Title"> 
                    </div>
                    
                        
                <div class="bg">
                   <div class="form-group">
                        <textarea type="text" class="form-control" name="description" placeholder="description"> </textarea>
                      </div>            
                </div>
                <div class="form-group">
                    <select name="tags" id="tc_input" class="form-control" id="">
                        @foreach($tags as $tag)
                         <option value="{{$tag->id}}">{{$tag->name}}</option>
                         @endforeach
                    </select>
                </div>
               
              <div class="bg">
                 <div class="form-group">
                     <input type="file" class="form-control" name="image" placeholder="image" style="background-color: #f5f8fa;"> 
                  </div>
              </div> 
             <br> 
            
             <button type="submit" class="btn btn-success btn-block">Submit</button>
               </form>
              </div>
              </div>
           <br>

          
          <div class="alert alert-info alert-dismissible fade show" role="alert">
          @forelse($forums as $forum)
          <b>Pertanyaan Terakhir Anda:</b><br>

           <a href="#" style="color: #444"><h5 style="margin-top: 4px;"><i class="fa fa-newspaper-o"></i> {{$forum->title}}</h5></a> 
           @empty
        <strong> Pertanyaan baru akan muncul disini.</strong><br> 
          @endforelse
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
            </div>
        </div>
    </div>
</div>
@endsection
 

StackOverflow/resources/views/forum/edit.blade.php
@extends('layouts.app')
@section('title',"Edit : $forum->title")
@section('content')
<div class="container">
    <div class="jumbotron" id="tc_jumbotron">
      <div class="col-md-8 offset-md-2">
        <div class="text-center"><h3 style="color: #000;">Edit Pertanyaan</h3></div><hr style="background: #000"> 
      </div>
    <div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card">
                <div class="card-body">
                  <form action="{{route('forum.update', $forum->id)}}" method="post" enctype="multipart/form-data">
                    {{csrf_field()}}
                    {{method_field('PUT')}}
                  <div class="form-group">
                      <input type="text" name="title" class="form-control" value="{{$forum->title}}">
                  </div>
                  <div class="form-group">
                      <textarea type="text" name="description" class="form-control" placeholder="Description..">{{$forum->description}}</textarea>
                  </div> 
                  <div class="form-group">
                    <select name="tags" class="form-control">
                        @foreach($tags as $tag)
                          <option value="{{$tag->id}}">{{$tag->name}}</option>
                        @endforeach
                    </select>
                  </div>      
                    <div id="edit_image">  
                        <div class="bg">
                          <div class="form-group">
                             <input type="file" class="form-control" name="image" placeholder="image" style="background-color: #f5f8fa;"> 
                                </div>
                            </div>  
                            @if (empty($forum->image))
                                <small><i class="fa fa-info-circle"></i>Tidak Ada Gambar</small> 
                            @else
                            <div class="form-group">
                               <div class="col-md-4"> 
                               <img src="{{asset('image/'.$forum->image)}}" alt="" width="100%">
                               </div>
                           </div>
                            @endif 
                          </div>
                           <br> 
                      <button type="submit" class="btn btn-success btn-block">Submit</button>
                   </form>
                </div>
            </div>
          <br> 
        <div class="alert alert-info alert-dismissible fade show" role="alert"> 
          <b>Pertanyaan terakhir edit:</b><br> 
           <a href="#" style="color: #444"><h5 style="margin-top: 4px;"><i class="fa fa-newspaper-o"></i> {{$forum->title}}</h5></a>  
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
       </div>
    </div>
  </div>
</div>
@endsection

StackOverflow/resources/views/forum/index.blade.php
@extends('layouts.app')
@section('title','Forum')
@section('content')
<div class="container">
  <div class="jumbotron" id="tc_jumbotron">
    <div class="card-body" id="xx" style="color: #000;     border:1px solid #000;">
        <div class="text-center"> 
           <h1 style="    font-size: 3.5rem;">STACK OVERFLOW</h1> 
        <p>Tugas SanberCode </p>  
          </div>
        </div> 
      </div> 
    </div>  
        <div class="container"> 
            <div class="row">
             <div class="col-md-12" id="tc_container_wrap">
            <div class="card" id="tc_paneldefault"> 
                <div class="card-body" id="tc_panelbody"  style="background: #f9f9f9;">  
               <div class="row">
               <div class="col-md-8" style="    padding-right: 0;"><br>
                <table class="table table-bordered">
              <thead id="tc_thead">
                <tr>
                  <th scope="col">Pertanyaan</th>
                  <th scope="col">Komentar</th>
                  <th scope="col"></th>
                  <th scope="col">Info</th>
                </tr>
              </thead>
              <tbody style="background: #f9f9f9;"> 
                @foreach($forums as $forum)
                <tr>
                <td width="453">
                <div class="forum_title">
                <h4><a href="{{route('forumslug', $forum->slug)}}">{{$forum->title}}</a></h4>
                <p>{{$forum->description}}</p>
                @foreach($forum->tags as $tag)
                <a href="#" class="badge badge-success tag_label">#{{$tag->name}}</a>
                @endforeach
                @if(empty($forum->image))
                @else
                 <div class="badge badge-success tag_label_image"><i class="fa fa-image"></i></div> 
                @endif
                </div> 
              </td>
               <td  style="text-align: center"><small> {{$forum->comments->count()}}</small></td>
              <td  style="text-align: center"><small> -</small></td>
              <td>
            <div class="forum_by">
            <small style="margin-bottom: 0; color: #666">2 min ago</small>
             <small><br>by <a href="#">{{$forum->user->name}}</a></small>
            </div>
            </td>
            </tr> 
            @endforeach
              </tbody>
            </table>
            <div class="row justify-content-center">
                 {!!$forums->links()!!}
            </div>
              </div>
                <div class="col-md-4"> <br>
                  <a href="{{route('forum.create')}}" class="btn btn-success btn-block">Buat Pertanyaan</a><br>
              
                </div>
                </div>
                <hr style="margin-top: 0;"> 
                <div class="card">
                <div class="card-header"></div>
                <div class="card-body" style="background: rgb(90, 90, 90)"></div>
                <div class="card-header"></div>
                </div>
            </div>
          </div>
        </div>
    </div>
</div><br><br>
@endsection
 

StackOverflow/resources/views/forum/show.blade.php
@extends('layouts.app')
@section('title',"$forums->title")
@section('content')
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
<div class="container">
  <div class="jumbotron" id="tc_jumbotron">
    <div class="card-body" id="xx">
        <div class="tc_head_title"> 
           <h2 style="color: #fff;">{{$forums->title}}</h2>  
        </div>
    </div>
  </div>
</div>  
<div class="container">
    <div class="row">
        <div class="col-md-12" id="tc_container_wrap">
            <div class="card" id="tc_paneldefault" style="background: #f9f9f9;"> 
                <div class="card-body" id="tc_panelbody">
                    <div class="row">
                        <div class="col-md-8">
                          <div class="card">
                             <div class="card-body" style="background: #f9f9f9;"> 
                      <div class="forum_info">
                     <div class="share pull-right">
                      <a href="#">  <i class="fa fa-facebook"></i></a>
                      <a href="#">  <i class="fa fa-twitter"></i></a>
                      <a href="#">  <i class="fa fa-google-plus"></i></a>
                      </div>
                    <a href="#" class="badge badge-success">{{$forums->user->name}}</a> |
                    <small>{{$forums->created_at->diffForHumans()}}</small> |
                    <small>{{$forums->comments->count()}} Comments</small> |
                    @foreach($forums->tags as $tag)
                    <div class="badge badge-success">#{{$tag->name}}</div>
                    @endforeach
                    @if (empty($forums->image))
                            @else
                          <div class="badge badge-success"><i class="fa fa-image"></i></div>
                           @endif
                    <h3>{{$forums->title}}</h3> 
                  </div>
                  <hr style="margin-top: 0; margin-bottom: 5px;">
                  <div class="forum_description">
                  @if (empty($forums->image))
                        @else
                        <br>
                    <div class="tc_if_empty">
                   <a data-target="#open_modal"><i id="zoom_image"></i></a>
                <div id="open_modal"> 
                  <div class="bg">
                    <img src="{{asset('image/'.$forums->image)}}" alt="" width="100%">
                    <div class="overlay">
                     <a href="#myModal" data-toggle="modal" data-target="#myModal"><h2>Zoom</h2> </a> 
                    </div>
                  </div>
                    </div>
                    </div>  
                       @endif
                    <p>{!!$forums->description!!}</p>
                  </div>
                </div>
              </div>
            <!-- Modal -->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Screenshot:</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body" id="modal_img">
                 <img src="{{asset('images/'.$forums->image)}}" alt="">
                  </div> 
                </div>
              </div>
            </div>

            <br>
            @forelse($forums->comments as $comment)
            <div class="card">
  <div class="card-header" style=" background-color: #2ab27b; color: #fff; border-top-right-radius: 0px; border-top-left-radius: 0px;"><i class="fa fa-clock-o" style="color: #eee"></i> <small style="color: #eee">2 min ago</small></div>
  <div class="card-body" style="background: #f9f9f9; "> 
    <div class="row">
      <div class="col-md-3" id="img_comment">
        <img src="{{asset('image/profile.jpg')}}" width="100%">
        <br>
        <div class="comment_user">
        <b>{{$comment->user->name}}</b>
        </div>
      </div>
      <div class="col-md-8">
      {{$comment->content}}
      </div>
    </div>
    <div class="button-gg"> 
      <button class="btn btn-Warning" type="submit">Tandai Benar </button>
     </div>
</div>
 <div>
  <div class="card-body">
    <!-- forelse reply-->
  @forelse($forums->replies as $reply)
  <div class="card">
      <div class="card-header" style="background-color: #2ab27b; color: #fff; border-top-right-radius: 0px; border-top-left-radius: 0px;"><i class="fa fa-clock-o" style="color: #eee"></i> <small style="color: #eee">2 min ago </small></div>
      <div class="card-body" style="background: #f9f9f9;"> 
        <div class="row">
      <div class="col-md-8">
      {{$reply->konten}}
      </div>
       <div class="col-md-3" id="img_comment_reply">
        <img src="{{asset('image/profile.jpg')}}" width="100%">
        <br>
        <div class="comment_user">
        <b>{{$comment->user->name}}</b>
        </div>
      </div>
    </div>
    </div>
    </div>
   </div>
   @empty
   <p>No Reply</p>
   @endforelse

      <div class="panel-body" style="    border-top: 1px solid #eee;">
      @if (Auth::guest())
          <a href="{{route('login')}}"><i class="fa fa-sign-in"></i> <p>Harap Login dahulu</p></a>
      @else
      <form action="{{route('addReply',$forums->id)}}" method="post">
      {{csrf_field()}}
      <div class="form-group">
      <input type="text" name="konten" id="Your-Answer" placeholder="Your Reply:" required="required">    
      </div>
      <button class="btn btn-success" type="submit">Submit</button>
      </form>
      @endif
      </div>
    </div>
  </div>
  @empty
  <p>No Comment</p>
  @endforelse
<!-- endforelse -->
  <hr>
            <hr>
            <div class="panel panel-default" style="background-color: #f9f9f9;">
              <div class="panel-body">
            <div class="add_comment">
                @if (Auth::guest())
                  <a href="{{route('login')}}"><i class="fa fa-sign-in"></i> <p>Harap Login dahulu</p></a>
                @else
                <form action="{{route('addComment',$forums->id)}}" method="post">
                  {{csrf_field()}}
                <div class="form-group">
                  <input type="text" name="content" id="Your-Answer" placeholder="Your Comment:" required="required">
                  <label for="Your-Comment">Your Comment:</label>    
                </div>
                <div class="button-gg"> 
                  <button class="btn btn-success" type="submit">Submit</button>
                </div>
              </form>
              @endif
            </div>
              </div>
            </div>
            </div>

@endsection

<!-- css -->

<style type="text/css">

input {
  font-family: inherit;
  -webkit-appearance: none;
  -moz-appearance: none;
  border: 0;
  border-bottom: 1px solid #AAAAAA;
  font-size: 16px;
  color: #000;
  border-radius: 0;
}

input[type="text"],
input[type="password"] {
  width: 100%;
  height: 40px;
      background: transparent;
}

button,
input:focus {
  outline: 0;
}

::-webkit-input-placeholder { 
  font-size: 16px;
  font-weight: 300;
  letter-spacing: -0.00933333em;
}

.form-group {
  position: relative;
  padding-top: 15px;
  margin-top: 10px;
}

label {
  position: absolute;
  top: 0;
  opacity: 1;
  -webkit-transform: translateY(5px);
          transform: translateY(5px);
  color: #aaa;
  font-weight: 300;
  font-size: 13px;
  letter-spacing: -0.00933333em;
  transition: all 0.2s ease-out;
}

input:placeholder-shown  + label {
  opacity: 0;
  -webkit-transform: translateY(15px);
          transform: translateY(15px);
}

.h1 {
  color: #999;
  opacity: 0.8;
  margin: 0;
  font-size: 15px;
  font-weight: 400;
  transition: all 770ms cubic-bezier(0.51, 0.04, 0.12, 0.99);
  text-align: center;
  cursor: pointer; 
}

.open .h1 {
  -webkit-transform: translateX(200px) translateZ(0);
          transform: translateX(165px) translateZ(0);
}

.h2 {
  color: #000;
  font-size: 20px;
  letter-spacing: -0.00933333em;
  font-weight: 600;
  padding-bottom: 15px;
}

.add_comment {
  height:160px;
  border-radius: 4px;
  overflow: hidden;
  position: relative;
}

.open_comment {
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  transition: all 770ms cubic-bezier(0.51, 0.04, 0.12, 0.99);
  overflow: hidden;
}

.open_comment img {
  object-fit: cover;
  width: 100%;
  height: 100%;
  display: block;
  transition: all 770ms cubic-bezier(0.51, 0.04, 0.12, 0.99);
  object-position: left;
}

.open .open_comment img {
  -webkit-transform: translateX(280px) translateZ(0);  
          transform: translateX(280px) translateZ(0);  
}

.open .open_comment {
  -webkit-transform: translateX(-400px) translateZ(0);
          transform: translateX(-400px) translateZ(0);
} 

.comment-show {
  position: absolute;
  top: 0;
  right: 0;
  width: 457px;
  -webkit-transform: translateX(400px) translateZ(0);
          transform: translateX(468px) translateZ(0);
  transition: all 770ms cubic-bezier(0.51, 0.04, 0.12, 0.99);
}

.open .comment-show {
  -webkit-transform: translateX(0px) translateZ(0);
          transform: translateX(0px) translateZ(0);
}

input[type="checkbox"] {
  cursor: pointer;
  margin: 0;
  height: 22px;
  position: relative;
  width: 22px;
  -webkit-appearance: none;
  transition: all 180ms linear;
}

input[type="checkbox"]:before {
    border: 1px solid #aaa;
    background-color: #fff;
    content: '';
    width: 20px;
    height: 20px;
    display: block;
    border-radius: 2px;
    transition: all 180ms linear;
}

input[type="checkbox"]:checked:before {
  background: linear-gradient(198.08deg, #B4458C 45.34%, #E281E7 224.21%);
  border: 1px solid #C359AA;
}

input[type="checkbox"]:after {
  content: '';
  border: 2px solid #fff;
  border-right: 0;
  border-top: 0;
  display: block;
  height: 4px;
  left: 4px;
  opacity: 0;
  position: absolute;
  top: 6px;
  -webkit-transform: rotate(-45deg);
          transform: rotate(-45deg);
  width: 12px;
  transition: all 180ms linear;
}

input[type="checkbox"]:checked:after {
    opacity: 1;
} 

.button-gg {
  margin-top: 20px;
}

.btn-primary {
  color: #fff;
  background: linear-gradient(198.08deg, #B4458C 45.34%, #E281E7 224.21%);
  box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.1);
}

.btn-secondary {
  color: #C359AA;  
}
.bg,
.overlay {
  text-align: center;
}
.bg .overlay  a{
  text-decoration: none;
}
img,
.overlay {
  transition: .3s all;
  border-radius: 3px;
}

.bg {
  /*float: left;*/
  max-width: 31%;
  position: relative;
  margin: .5%;
}
.bg img {
  width: 100%;
  margin-bottom: -4px;
}
.bg .overlay {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  width: 100%;
  background: rgba(0, 0, 0, 0.2);
  color: #fff;
  opacity: 0;
}
.bg .overlay h2 {
  padding-top: 14%;
  color: #fff; 
}
.bg .overlay p {
  font-family: 'Julius Sans One', sans-serif;
}
.bg:hover .overlay {
  opacity: 1;
}
.bg:hover img {
  -webkit-filter: blur(2px);
  filter: blur(2px);
}

@media screen and (max-width: 1148px) {
  .bg {
    max-width: 48%;
    margin: 1%;
  }
}
@media screen and (max-width: 768px) {
  .bg {
    float: none;
    max-width: 80%;
    margin: 1% auto;
  }
}
  
</style>

@section('js')
<script type="text/javascript">
var openComment = document.querySelector('.h1');
var addComment = document.querySelector('.add_comment');
openComment.addEventListener('click', function(){
  addComment.classList.toggle('open'); 
});

</script>
@endsection

StackOverflow/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

StackOverflow/resources/views/layouts/info.blade.php
@if(count($errors)>0)
<div class="alert alert-danger">
    <ul>
        @foreach($errors->all() as $error)
            <li>{{$error}}</li>
        @endforeach
@endif

@if(session('info'))
    <div class="alert alert-success">
            <i class="fa fa-check"></i> {{session('info')}}
    </div>
@endif